routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\PostController::class, 'index']);
Route::get('/users', [App\Http\Controllers\UserController::class, 'index']);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function getExcerptAttribute()
    {
        return substr($this->body, 0, 120);
    }

    public function getPublishedAtAttribute()
    {
        return $this->created_at->format('d-m-Y');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        return view('index', [
            'posts' => Post::latest()->paginate(10)
        ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        return view('user.user', [
            'users' => User::latest()->paginate(10)
        ]);
    }
}

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Post your posts</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body class="bg-purple-300 text-black-700 ">
    <div>
        <h1 class="text-center mt-10 text-5xl font-extrabold">Post Your Posts</h1>
    </div>
    <div class="container mx-auto px-4">
        <div class="grid grid-cols-3 my-10">
            @foreach($posts as $post)
            <div class="bg-white hover:bg-green-300 border border-gray-200 rounded-lg p-5 mb-4">
                <p class="text-xs text-right text-blue-900 underline">{{ $post->published_at }}</p>
                <h3 class="font-bold text-md mb-4"><b class="text-purple-600">Title:</b> {{ $post->title }}</h3>
                <span class="text-xs">{{ $post->excerpt }}</span>
            </div>
            @endforeach
        </div>

        <div class="mb-10">
            {{ $posts->links() }}
        </div>
    </div>

</body>

</html>

resources/views/user/user.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Post your posts</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body class="bg-purple-300 text-black-700">
    <div>
        <h1 class="text-center mt-10 text-5xl font-extrabold">Users</h1>
    </div>
    <div class="container mx-auto px-4">
        <div class="grid grid-cols-2 my-10">
            @foreach($users as $user)
            <ul class="bg-white hover:bg-yellow-100 border border-pink-500 rounded-lg p-5 mb-4">
                <li class="text-center text-purple-900"><b>{{ $user->name }}</b></li>
                <li class="text-xs text-right text-blue-900">{{ $user->email }}</li>
            </ul>
            @endforeach
        </div>

        <div class="mb-10">
            {{ $users->links() }}
        </div>
    </div>

</body>

</html>